"""
Changing the name of the password column

Revision ID: 09bc879baf5a
Revises: d464322822a0
Create Date: 2022-04-26 11:18:32.341695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09bc879baf5a'
down_revision = 'd464322822a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal', sa.Column('password_hash', sa.String(), nullable=False))
    op.drop_column('personal', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('personal', 'password_hash')
    # ### end Alembic commands ###
