"""Update equipament and exercicio relationship and codigo equipment unique

Revision ID: 179abd4c9b87
Revises: 9cf16f284ed9
Create Date: 2022-05-03 16:37:35.755250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179abd4c9b87'
down_revision = '9cf16f284ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'equipment', ['codigo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment', type_='unique')
    # ### end Alembic commands ###
