"""creating enum

Revision ID: 4c3aaeac1db5
Revises: ae8fb1bf6420
Create Date: 2022-05-02 17:16:00.834875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3aaeac1db5'
down_revision = 'ae8fb1bf6420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'equipment', ['nome'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment', type_='unique')
    # ### end Alembic commands ###
