"""unique property of the phone column of the student table changed

Revision ID: ae1a8728cd55
Revises: 179abd4c9b87
Create Date: 2022-05-05 12:12:26.356961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1a8728cd55'
down_revision = '179abd4c9b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('aluno_telefone_key', 'aluno', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('aluno_telefone_key', 'aluno', ['telefone'])
    # ### end Alembic commands ###
