"""creating execucao model

Revision ID: ae8fb1bf6420
Revises: ca74f7aaba18
Create Date: 2022-04-27 18:38:12.512451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8fb1bf6420'
down_revision = 'ca74f7aaba18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercicio', 'carga')
    op.drop_column('exercicio', 'series')
    op.drop_column('exercicio', 'repeticoes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercicio', sa.Column('repeticoes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercicio', sa.Column('series', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercicio', sa.Column('carga', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
