"""creating training and exercices models and pivot tabel

Revision ID: ca74f7aaba18
Revises: f678911756a5
Create Date: 2022-04-27 12:04:21.925398

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ca74f7aaba18"
down_revision = "f678911756a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercicio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("series", sa.Integer(), nullable=True),
        sa.Column("repeticoes", sa.Integer(), nullable=True),
        sa.Column("carga", sa.String(), nullable=True),
        sa.Column("estimulo", sa.String(), nullable=True),
        sa.Column("aparelho_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["aparelho_id"],
            ["equipment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "treino",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("dia", sa.String(), nullable=False),
        sa.Column("personal_id", sa.Integer(), nullable=True),
        sa.Column("aluno_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["aluno_id"],
            ["aluno.id"],
        ),
        sa.ForeignKeyConstraint(
            ["personal_id"],
            ["personal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "treino_exercicio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("treino_id", sa.Integer(), nullable=True),
        sa.Column("exercicio_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercicio_id"],
            ["exercicio.id"],
        ),
        sa.ForeignKeyConstraint(
            ["treino_id"],
            ["treino.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("treino_exercicio")
    op.drop_table("treino")
    op.drop_table("exercicio")
    # ### end Alembic commands ###
