"""Execucao model

Revision ID: ecd6b7e95ff2
Revises: 4c3aaeac1db5
Create Date: 2022-05-03 11:38:33.805796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd6b7e95ff2'
down_revision = '4c3aaeac1db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execucao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticoes', sa.Integer(), nullable=True),
    sa.Column('carga', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execucao')
    # ### end Alembic commands ###
